### ISSUE TITLE
Build error on OSX 10.10

### ISSUE THREAD

**Issue by dpo** [arrayfire/forge#73]
I'm trying to update the Homebrew formula for `arrayfire` to version 3.2.2. In the process, I'm using version af3.2.2 of `forge`. It compiles on OSX 10.9 and 10.11, but not on 10.10. Using clang++, I get the error message:
```
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers/CGLCurrent.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers/CGLTypes.h:75:15: error: missing ',' between enumerators
        kCGLPFAStereo OPENGL_ENUM_DEPRECATED(10_0, 10_11)        =   6,
                     ^
                     , 
```
You can find the full build log [here](https://travis-ci.org/Homebrew/homebrew-science/jobs/100037999).
The error above is located [here](https://travis-ci.org/Homebrew/homebrew-science/jobs/100037999#L1713).

Thanks in advance for any clue!

**Comment by 9prady9** [comment]
@dpo I have tried forge build on the following machine and it built fine for me.
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F27
```

I build with the following clang version
```
$ c++ --version
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

Not really sure, what is the difference between your dev environment and mine ? Could it be travis ci setup ?

**Comment by dpo** [comment]
Thanks for checking. I'm not sure what's going on. It's not only Travis. The Homebrew build bot reports the same issue. I'll dig more.

**Comment by pavanky** [comment]
This is what we have on our build machine.
```
$ ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
MacOSX10.10.sdk MacOSX10.9.sdk
```

Travis is building with MacOSX10.11sdk. Could that be the issue?

**Comment by dpo** [comment]
It could be. Unfortunately, I only have access to 10.10 on Travis or the build bot.

**Comment by dpo** [comment]
Here too things seem to have been resolved, perhaps by an OS update. Thanks! For reference, I was having the same error as described here: http://comments.gmane.org/gmane.comp.compilers.clang.devel/46074

**Comment by 9prady9** [comment]
glad that it got fixed and wasn't a bug in the code! :)
